In [167]:
import matplotlib.pyplot as plt
import collections as cl
import numpy as np
import seaborn as sns
import pandas as pd
import plotly.express as px

In [168]:
path1 = "datasets/AppleStore.csv"
dat1 = pd.read_csv(path1)
dfApple = pd.DataFrame(dat1)
dfApple.head()

,Unnamed: 0,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
0,1,281656475,PAC-MAN Premium,100788224,USD,3.99,21292,26,4.0,4.5,6.3.5,4+,Games,38,5,10,1
1,2,281796108,Evernote - stay organized,158578688,USD,0.00,161065,26,4.0,3.5,8.2.2,4+,Productivity,37,5,23,1
2,3,281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,USD,0.00,188583,2822,3.5,4.5,5.0.0,4+,Weather,37,5,3,1
3,4,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,USD,0.00,262241,649,4.0,4.5,5.10.0,12+,Shopping,37,5,9,1
4,5,282935706,Bible,92774400,USD,0.00,985920,5320,4.5,5.0,7.5.1,4+,Reference,37,5,45,1

In [169]:
dfApple = dfApple.drop(columns = ["currency", "id", "vpp_lic", "ver", "Unnamed: 0","lang.num", "user_rating_ver","rating_count_ver", "sup_devices.num","ipadSc_urls.num"])

In [170]:
dfApple.head()

,track_name,size_bytes,price,rating_count_tot,user_rating,cont_rating,prime_genre
0,PAC-MAN Premium,100788224,3.99,21292,4.0,4+,Games
1,Evernote - stay organized,158578688,0.00,161065,4.0,4+,Productivity
2,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,0.00,188583,3.5,4+,Weather
3,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,0.00,262241,4.0,12+,Shopping
4,Bible,92774400,0.00,985920,4.5,4+,Reference

In [171]:
#data cleaning
#free or not
dfApple = dfApple.rename(columns = {"rating_count_tot": "Reviews", "user_rating" : "Rating", "cont_rating" : "Content Rating",
                          "prime_genre" : "Category", "price" : "Price", "size_bytes" : "Size", "track_name" : "App"})
dfApple["Type"] = "1"

In [172]:
dfApple["Category"].unique()

array(['Games', 'Productivity', 'Weather', 'Shopping', 'Reference',
       'Finance', 'Music', 'Utilities', 'Travel', 'Social Networking',
       'Sports', 'Business', 'Health & Fitness', 'Entertainment',
       'Photo & Video', 'Navigation', 'Education', 'Lifestyle',
       'Food & Drink', 'News', 'Book', 'Medical', 'Catalogs'],
      dtype=object)

In [173]:
dfApple[dfApple['Category'] == 'Games']

,App,Size,Price,Reviews,Rating,Content Rating,Category,Type
16,Facebook,389879808,0.00,2974676,3.5,4+,Social Networking,1
30,LinkedIn,273844224,0.00,71856,3.5,4+,Social Networking,1
91,Skype for iPhone,133238784,0.00,373519,3.5,4+,Social Networking,1
92,Tumblr,151573504,0.00,334293,4.0,17+,Social Networking,1
94,Match™ - #1 Dating App.,101259264,0.00,60659,3.0,17+,Social Networking,1
...,...,...,...,...,...,...,...,...
7062,LINE BLOG,101159936,0.00,0,0.0,12+,Social Networking,1
7130,Mustknow - anonymous video Q&A,92884992,0.00,53,1.5,12+,Social Networking,1
7156,Demi Lovato Stickers,88388608,0.99,12,3.5,12+,Social Networking,1
7170,CTFxCmoji,26077184,0.00,39,5.0,9+,Social Networking,1
7179,Fam — Group video calling for iMessage,113382400,0.00,279,3.5,4+,Social Networking,1

In [174]:
dfApplefree = dfApple[dfApple["Price"] == 0] 
dfApplepaid = dfApple[dfApple["Price"] > 0]
dfApplepaid["Type"] = "1"
dfApplefree["Type"] = "0"
dfAppleclean = pd.concat([dfApplefree, dfApplepaid])
dfAppleclean["Category"].unique()

<ipython-input-174-49735fa523a6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfApplepaid["Type"] = "1"
<ipython-input-174-49735fa523a6>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfApplefree["Type"] = "0"

array(['Productivity', 'Weather', 'Shopping', 'Reference', 'Finance',
       'Music', 'Utilities', 'Travel', 'Social Networking', 'Sports',
       'Health & Fitness', 'Games', 'Food & Drink', 'News', 'Book',
       'Photo & Video', 'Entertainment', 'Business', 'Lifestyle',
       'Education', 'Navigation', 'Medical', 'Catalogs'], dtype=object)

In [175]:
#clean content rating
def cleanContent(x):
    if x == "4+":
        return "Everyone"
    elif x == "9+":
        return "Everyone 10+"
    elif x == "12+":
        return 'Teen'
    elif x == "17+":
        return 'Mature 17+'

def cleanCategory(x):
    if x == "Reference" or x == "Book":
        return "Books & Reference"
    else:
        return x

In [176]:
dfApple = dfAppleclean
dfApple["Content Rating"] = dfApple["Content Rating"].replace([x for x in dfApple["Content Rating"]], [cleanContent(x) for x in dfApple["Content Rating"]])
dfApple["Category"] = dfApple["Category"].replace([x for x in dfApple["Category"]], [cleanCategory(x) for x in dfApple["Category"]])

In [178]:
dfApple.head()

,App,Size,Price,Reviews,Rating,Content Rating,Category,Type
1,Evernote - stay organized,158578688,0.0,161065,4.0,Everyone,Productivity,0
2,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,0.0,188583,3.5,Everyone,Weather,0
3,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,0.0,262241,4.0,Teen,Shopping,0
4,Bible,92774400,0.0,985920,4.5,Everyone,Books & Reference,0
6,PayPal - Send and request money safely,227795968,0.0,119487,4.0,Everyone,Finance,0